# Site settings
title: Gabe's Workspace
email: gabe.l.cohen@gmail.com
description: > # Welcome to my site. I'm a Computer Science Student at UC San Diego.
 I like Software Engineering, enjoy data, playing chess, and making people laugh!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://glcohen.github.io" # the base hostname & protocol for your site
github_username:  glcohen
twitter_username: gabe_l_cohen

# Build settings
markdown: kramdown
